### ISSUE TITLE
Matrix multiplication error for annual three phase run

### ISSUE THREAD

**Issue by sariths** [LBNL-ETA/frads#24]
A three phase annual simulation fails with matrix multiplication errors. For example, this code snippet: 

![image](https://github.com/LBNL-ETA/frads/assets/10361848/77a8fd8e-f1a6-4035-88d6-8f50e4e9e316)

.. fails with the following error. 
![image](https://github.com/LBNL-ETA/frads/assets/10361848/f7b864ca-1ab3-4c7d-a6d8-7a8426ec552a)

The traceback leads to the following [line](https://github.com/LBNL-ETA/frads/blob/develop/frads/methods.py#L533-L543): 
![image](https://github.com/LBNL-ETA/frads/assets/10361848/aba0c87d-1d77-4b0d-b806-746802421bd8)

**Comment by taoning** [comment]
close when merge to main
