### ISSUE TITLE
Implement specific actuator

### ISSUE THREAD

**Issue by taoning** [LBNL-ETA/frads#42]
Based on the current generic implementation of EnergyPlusSetup.actuate, implement some commonly used actuators such as:

- actuate_construction_state(surface_name, state)
- actuate_heating_setpoint(zone_name, value)
- actuate_cooling_setpoint(zone_name, value)
- actuate_lighting_power(zone_name, value)

**Comment by TammieYu** [comment]
[ba36733](https://github.com/LBNL-ETA/frads/pull/43/commits/ba367337684ace5fa7ab086abd6605704404b0e4)
